### ISSUE TITLE
TRG 2.04 Leading Product Repository

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/portal-cd#116]
Hi,

we stumbled upon this on and off and i don't think we ever mentioned it:

But the idea of TRG 2.04 is to have at least on leading repository without any suffix or prefix to make it immediadly clear what the main repository per product is:

https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4/

Please consider renaming this project to portal

**Comment by carslen** [comment]
See comment in #131
