### ISSUE TITLE
Release Candidate 1.8.0 RC3 (due week 4)

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-cd#150]
## Summary

Build the new release candidate of "portal" (see components below) and deploy to consortia integration env.
Execute the release process in the eclipse-tractusx organisation.
Branch: Release Branch

Tasks:

~~- [ ] merge migration~~ no new migration for RC3
- [x] changelog backend
- [x] changelog frontend
~~- [ ] changelog registration~~ wasn't part of RC3
- [x] changelog assets
- [x] release backend (version bump, push tag, create GH release, merge relesae branch)
- [x] release frontend (version bump, push tag, create GH release, merge relesae branch)
~~- [ ] release registration (version bump, push tag, create GH release, merge relesae branch)~~ wasn't part of RC3
- [x] release assets (version bump, push tag, create GH release, merge relesae branch)
- [x] release cd (version bump, changelog, update readme, release new helm chart, merge relesae branch)
- [x] provide successive RC branch (tractusx und ng-forks)
- [x] change base of open PRs
- [x] Sync main and dev branches in ng-forks
- [x] user info
- [x] deploy to integration environment
- [x] run test automation
- [x] validate results
- [x] inform team members of the deployment status

**Comment by evegufy** [comment]
[done](https://github.com/eclipse-tractusx/portal-cd/tree/portal-1.8.0-RC3/charts/portal#helm-chart-for-catena-x-portal)

**Comment by jjeroch** [comment]
@evegufy status is incorrect, updated it. Test automation run outstanding. @Phil91 can you please run it and validate the results. Thanks
