### ISSUE TITLE
Release Candidate 1.8.0 RC4 (due week 5)

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-cd#151]
## Summary

Build the new release candidate of "portal" (see components below) and deploy to consortia integration env.
Execute the release process in the eclipse-tractusx organisation.
Branch: Release Branch

Tasks:

~~- [ ] merge migration~~ no new migration for RC4
- [x] changelog backend
- [x] changelog frontend
- [x] changelog registration
- [x] changelog assets
- [x] release backend (version bump, push tag, create GH release, merge relesae branch)
- [x] release frontend (version bump, push tag, create GH release, merge relesae branch)
- [x] release registration (version bump, push tag, create GH release, merge relesae branch)
- [x] release assets (version bump, push tag, create GH release, merge relesae branch)
- [x] release cd (version bump, changelog, update readme, release new helm chart, merge relesae branch)
- [x] provide successive RC branch (tractusx und ng-forks)
- [x] change base of open PRs
- [x] Sync main and dev branches in ng-forks
- [x] user info
- [x] deploy to integration environment
- [x] run test automation
- [x] validate results
- [x] inform team members of the deployment status

**Comment by jjeroch** [comment]
RC blockers:
https://github.com/eclipse-tractusx/portal-frontend/issues/454

### ChangeLogs
- [ ] Assets: ongoing
- [ ] PolicyHub: n/a
- [ ] Backend: ongoing
- [ ] Frontend: https://github.com/catenax-ng/tx-portal-frontend/compare/release/v1.8.0-RC3...release/changeLog-1.8.0-RC3
- [ ] Registration: https://github.com/catenax-ng/tx-portal-frontend-registration/compare/release/v1.6.0-RC3...release/changeLog-1.8.0-RC3 

Test Automation on rc.dev: not possible

**Comment by evegufy** [comment]
Release [done](https://github.com/eclipse-tractusx/portal-cd/tree/portal-1.8.0-RC4/charts/portal#helm-chart-for-catena-x-portal).
Test automation run outstanding. @Phil91 can you please run it and validate the results. Thanks

**Comment by Phil91** [comment]
@evegufy @jjeroch I did run the e2e tests, result looks good from my point of view. we have 5 errors (prs for them are already created and pending, with exception of the user roles bug)
