### ISSUE TITLE
Connector Registration blocked

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-cd#180]
Detected in version: **1.8.0 RC-5**

With the latest release candidate the connector registration function got negatively impacted.
The connector registration is running on error:

### Request API
https://portal-backend.int.demo.catena-x.net/api/administration/connectors

### Request Body
```
Name: JJTestDelete
ConnectorUrl: https://www.google.de
Location: DE
Status: PENDING
```

### Error Response
```
"An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set."
```

### Screenshot
<img width="1710" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/444a34f3-aa24-4a4e-9cca-eca7e9989916">

**Comment by Phil91** [comment]
@jjeroch moved this ticket to the cd repo since we're doing the fixes here

**Comment by Phil91** [comment]
@jjeroch due to this issue all external service calls will fail
