### ISSUE TITLE
QG4: TRG 2.03 - Repo structure

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/portal-cd#70]
Hey @evegufy,

Testing Quality Guideline: TRG 2.03 - Repo structure

Warning! Guideline description: All repositories must follow specified files and folders structure.
	The check detected following optional files missing: AUTHORS.md, INSTALL.md
	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3

Failed! Guideline description: All repositories must follow specified files and folders structure.
	The check detected following mandatory files missing: **DEPENDENCIES, docs**
	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3

**Comment by evegufy** [comment]
No DEPENDENCIES file available because this repository only containing a helm chart.
docs is available in the portal-assets repository as noted in the README file https://github.com/eclipse-tractusx/portal-cd/blob/portal-1.6.0-RC7/README.md?plain=1#L19
